server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelratinguserdb
    username: root
    password: Amiya122001
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
#  application:
#    name: USER-MS
  config:
    import: optional:http://localhost:8085
  profiles:
    active: dev
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      ratingHotelRateLimiter:
        limit-refresh-period: 5s
        limit-for-period: 2
        timeout-duration: 1s
            


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
    